---
- hosts: all
  tasks:
  - name: upgrade all packages
    apt: upgrade=dist
    sudo: True

  - name: Install apt-get https
    apt: name=apt-transport-https state=present
    sudo: True

  - name: Add docker repo key
    command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
    sudo: True

  - name: Add docker repo
    command: sh -c "echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
    sudo: True

  - name: Install docker
    apt: update_cache=yes name=lxc-docker state=present
    sudo: True
   
  - name: Start docker service
    service: name=docker state=started

